sudo: required
dist: trusty

language: c++

install:
    - sudo apt-get install libgtest-dev build-essentials
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/local/lib/
    - cd -

compiler:
    - g++
    - clang

script: 
    - mkdir build
    - cd build 
    - cmake ../src && make
