sudo: required
dist: trusty

language: c++

before-install:
    - sudo apt-get install libgtest-dev libgtest

compiler:
    - g++
    - clang

script: 
    - mkdir build
    - cd build 
    - cmake ../src && make
